### ISSUE TITLE
Issue when patching with Illusory Mod Manager

### ISSUE THREAD

**Issue by adwilsher** [rodriada000/SessionMapSwitcher#17]
Hi,

I'm getting a similar issue to the previous commenter. When running Session through the mod manager, version 2.6.1.0, and patching with Illusory, I also get a "corrupted data found, please verify your game files" error, followed by a UE4 crash.

This happens even when no mods have been applied. It also now happens when trying to run the game through steam, instead of launching from the mod manager.

I've done some digging, and it looks like Illusory is putting a .dll file in the Win64 folder. When I delete this, I am then able to run vanilla Session, but not use the mod manager.

Any advice you can provide would be really kind! I've attached some snips to provide some context.

Please let me know if you need more info. :)

![Capture](https://user-images.githubusercontent.com/64497979/80530595-27402580-8991-11ea-8497-1a490ecce9eb.PNG)
![Capture-2](https://user-images.githubusercontent.com/64497979/80530602-29a27f80-8991-11ea-83c9-a7f3a63c66a0.PNG)
![Capture-3](https://user-images.githubusercontent.com/64497979/80530608-2b6c4300-8991-11ea-9a60-9b55244a8b3d.PNG)

**Comment by rodriada000** [comment]
Hi there. That message indicates you have an incompatible mod installed (a lot of the mods are now incompatible with 0.0.0.5 update as of right now).

The easiest way to fix that issue is by navigating to your `Session/SessionGame/Content` folder and deleting everything except `Paks` and `Movies` folder.

Note: when you apply the patch it creates that `dxgi.dll` so the mods can be injected into the game so that is required for patching/modding

**Comment by adwilsher** [comment]
Thanks for getting back to me so soon!

I'll have a crack at that tomorrow, and let you know if the fix works. 😄

**Comment by adwilsher** [comment]
Hi Adam,

All working good after removing those folders, thank you!

Many Thanks
Adam

**Comment by animester** [comment]
i have the same issue, made de same thing and the error persists

**Comment by Javierdelmoral** [comment]
same here...
