### ISSUE TITLE
Currupted data found 

### ISSUE THREAD

**Issue by Kenny208** [rodriada000/SessionMapSwitcher#18]
Hey guys, my problem is that my game doesn't want to start when I load a modded map and show the error currupted data.  How can I fix it? thanks in advance :)

**Comment by rodriada000** [comment]
please see issue #17 It is due to the modded map not being compatible with the latest session 0.0.0.5. As of now, only three maps are working for the latest update _(as of 4/28)_:
- Dust2
- Blokto Park
- Oak Town Park 

All three are available to download in the asset store in [SMM 2.6.2](https://github.com/rodriada000/SessionMapSwitcher/releases/tag/v2.6.2)

**Comment by Kenny208** [comment]
Thank you :)
